# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  libgkit3_config = debug
  tp1_config = debug
  tp2_config = debug
endif
ifeq ($(config),release)
  libgkit3_config = release
  tp1_config = release
  tp2_config = release
endif

PROJECTS := libgkit3 tp1 tp2

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

libgkit3:
ifneq (,$(libgkit3_config))
	@echo "==== Building libgkit3 ($(libgkit3_config)) ===="
	@${MAKE} --no-print-directory -C . -f libgkit3.make config=$(libgkit3_config)
endif

tp1: libgkit3
ifneq (,$(tp1_config))
	@echo "==== Building tp1 ($(tp1_config)) ===="
	@${MAKE} --no-print-directory -C . -f tp1.make config=$(tp1_config)
endif

tp2: libgkit3
ifneq (,$(tp2_config))
	@echo "==== Building tp2 ($(tp2_config)) ===="
	@${MAKE} --no-print-directory -C . -f tp2.make config=$(tp2_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f libgkit3.make clean
	@${MAKE} --no-print-directory -C . -f tp1.make clean
	@${MAKE} --no-print-directory -C . -f tp2.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   libgkit3"
	@echo "   tp1"
	@echo "   tp2"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"