# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  libgkit3_config = debug
  projet_config = debug
endif
ifeq ($(config),release)
  libgkit3_config = release
  projet_config = release
endif

PROJECTS := libgkit3 projet

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

libgkit3:
ifneq (,$(libgkit3_config))
	@echo "==== Building libgkit3 ($(libgkit3_config)) ===="
	@${MAKE} --no-print-directory -C . -f libgkit3.make config=$(libgkit3_config)
endif

projet: libgkit3
ifneq (,$(projet_config))
	@echo "==== Building projet ($(projet_config)) ===="
	@${MAKE} --no-print-directory -C . -f projet.make config=$(projet_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f libgkit3.make clean
	@${MAKE} --no-print-directory -C . -f projet.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   libgkit3"
	@echo "   projet"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"